const H={'content-type':'application/json; charset=utf-8','cache-control':'no-store'}, COOKIE='akari_session', enc=new TextEncoder();
export default{async fetch(req,env){const u=new URL(req.url);try{if(u.pathname.startsWith('/api/'))return await api(req,env,u);if(u.pathname.startsWith('/media/'))return await media(req,env,u);return env.ASSETS.fetch(req)}catch(e){console.error(e);return json({error:'サーバーで問題が発生しました。'},500)}}};

async function api(req,env,u){
 if(u.pathname==='/api/public/store'&&req.method==='GET')return publicData(env);
 if(u.pathname==='/api/auth/status'&&req.method==='GET')return authStatus(req,env);
 if(u.pathname==='/api/auth/setup'&&req.method==='POST')return setup(req,env);
 if(u.pathname==='/api/auth/login'&&req.method==='POST')return login(req,env);
 if(u.pathname==='/api/auth/logout'&&req.method==='POST')return logout(req,env);
 const session=await getSession(req,env);if(!session)return json({error:'ログインが必要です。'},401);if(!sameOrigin(req))return json({error:'不正なリクエストです。'},403);
 if(u.pathname==='/api/admin/dashboard'&&req.method==='GET')return dashboard(env);
 if(u.pathname==='/api/admin/status'&&req.method==='PATCH')return updateStatus(req,env);
 if(u.pathname==='/api/admin/store'&&req.method==='PATCH')return updateStore(req,env);
 if(u.pathname==='/api/admin/menus'&&req.method==='POST')return createMenu(req,env);
 if(u.pathname==='/api/admin/upload'&&req.method==='POST')return upload(req,env);
 const m=u.pathname.match(/^\/api\/admin\/menus\/([^/]+)$/);if(m&&req.method==='PATCH')return updateMenu(req,env,decodeURIComponent(m[1]));if(m&&req.method==='DELETE')return deleteMenu(env,decodeURIComponent(m[1]));
 return json({error:'見つかりません。'},404)
}
async function publicData(env){const store=await env.DB.prepare('SELECT * FROM stores WHERE id=1').first(),{results:menus}=await menuQuery(env);return json({store,menus},200,{'cache-control':'public, max-age=20, stale-while-revalidate=60'})}
async function dashboard(env){const store=await env.DB.prepare('SELECT * FROM stores WHERE id=1').first(),{results:menus}=await menuQuery(env,true);return json({store,menus})}
function menuQuery(env,admin=false){return env.DB.prepare(`SELECT id,name,price,category,description,COALESCE(image_url,CASE WHEN image_key IS NOT NULL THEN '/media/'||image_key ELSE '/assets/ramen-hero.png' END) image,${admin?'image_key imageKey,display_order displayOrder,':''}badge,sold_out soldOut FROM menus WHERE store_id=1 ORDER BY display_order,created_at`).all()}
async function authStatus(req,env){const n=await env.DB.prepare('SELECT COUNT(*) count FROM admin_users').first(),s=await getSession(req,env);return json({authenticated:!!s,setupRequired:Number(n.count)===0,username:s?.username||null})}
async function setup(req,env){if(!sameOrigin(req))return json({error:'不正なリクエストです。'},403);const n=await env.DB.prepare('SELECT COUNT(*) count FROM admin_users').first();if(Number(n.count))return json({error:'初期設定は完了しています。'},409);const b=await body(req);if(!env.SETUP_TOKEN||!equal(b.setupToken||'',env.SETUP_TOKEN))return json({error:'セットアップトークンが違います。'},403);const er=credentials(b.password);if(er)return json({error:er},400);const salt=random(16),iterations=210000,hash=await passHash(b.password,salt,iterations);await env.DB.prepare('INSERT INTO admin_users(id,username,password_hash,password_salt,iterations) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),'admin',hash,salt,iterations).run();return json({ok:true},201)}
async function login(req,env){if(!sameOrigin(req))return json({error:'不正なリクエストです。'},403);const b=await body(req),key=await sha(req.headers.get('CF-Connecting-IP')||'local'),a=await env.DB.prepare('SELECT * FROM login_attempts WHERE key=?').bind(key).first();if(a?.blocked_until&&new Date(a.blocked_until)>new Date())return json({error:'試行回数が多すぎます。15分後にお試しください。'},429);const user=await env.DB.prepare('SELECT * FROM admin_users ORDER BY created_at LIMIT 1').first(),valid=user&&equal(await passHash(String(b.password||''),user.password_salt,user.iterations),user.password_hash);if(!valid){await fail(env,key,a);return json({error:'パスワードが違います。'},401)}await env.DB.prepare('DELETE FROM login_attempts WHERE key=?').bind(key).run();const token=random(32),hash=await sha(token),days=Math.max(1,Math.min(30,Number(env.SESSION_DAYS)||14)),exp=new Date(Date.now()+days*86400000);await env.DB.batch([env.DB.prepare('INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,?)').bind(hash,user.id,exp.toISOString()),env.DB.prepare('UPDATE admin_users SET last_login_at=CURRENT_TIMESTAMP WHERE id=?').bind(user.id),env.DB.prepare('DELETE FROM sessions WHERE expires_at<CURRENT_TIMESTAMP')]);return json({ok:true},200,{'set-cookie':`${COOKIE}=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${days*86400}`})}
async function logout(req,env){if(!sameOrigin(req))return json({error:'不正なリクエストです。'},403);const t=cookie(req,COOKIE);if(t)await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await sha(t)).run();return json({ok:true},200,{'set-cookie':`${COOKIE}=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0`})}
async function updateStatus(req,env){const b=await body(req),notes={available:'すぐにご案内できます',busy:'5〜15分ほどお待ちいただきます',full:'ご案内までお時間をいただきます',closed:'現在は営業時間外です'};if(!notes[b.status])return json({error:'空き状況が正しくありません。'},400);await env.DB.prepare('UPDATE stores SET status=?,status_note=?,status_updated_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=1').bind(b.status,notes[b.status]).run();return json({ok:true})}
async function updateStore(req,env){const b=await body(req),f=['name','tagline','description','address','postal_code','phone','business_hours','regular_holiday','seats','map_url'];if(!b.name?.trim())return json({error:'店名を入力してください。'},400);await env.DB.prepare(`UPDATE stores SET ${f.map(x=>x+'=?').join(',')},updated_at=CURRENT_TIMESTAMP WHERE id=1`).bind(...f.map(x=>String(b[x]||'').trim())).run();return json({ok:true})}
async function createMenu(req,env){const b=await body(req),er=menuError(b);if(er)return json({error:er},400);const id=crypto.randomUUID(),max=await env.DB.prepare('SELECT COALESCE(MAX(display_order),0) n FROM menus WHERE store_id=1').first();await env.DB.prepare('INSERT INTO menus(id,name,price,category,description,image_key,image_url,badge,sold_out,display_order) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(id,b.name.trim(),Number(b.price),b.category,String(b.description||'').trim(),b.imageKey||null,b.imageKey?null:(b.image||'/assets/ramen-hero.png'),String(b.badge||'').trim(),b.soldOut?1:0,Number(max.n)+10).run();return json({ok:true,id},201)}
async function updateMenu(req,env,id){const b=await body(req),er=menuError(b);if(er)return json({error:er},400);const old=await env.DB.prepare('SELECT image_key FROM menus WHERE id=? AND store_id=1').bind(id).first();if(!old)return json({error:'メニューが見つかりません。'},404);await env.DB.prepare('UPDATE menus SET name=?,price=?,category=?,description=?,image_key=?,image_url=?,badge=?,sold_out=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND store_id=1').bind(b.name.trim(),Number(b.price),b.category,String(b.description||'').trim(),b.imageKey||null,b.imageKey?null:(b.image||'/assets/ramen-hero.png'),String(b.badge||'').trim(),b.soldOut?1:0,id).run();if(old.image_key&&old.image_key!==b.imageKey)await env.IMAGES.delete(old.image_key);return json({ok:true})}
async function deleteMenu(env,id){const old=await env.DB.prepare('SELECT image_key FROM menus WHERE id=? AND store_id=1').bind(id).first();if(!old)return json({error:'メニューが見つかりません。'},404);await env.DB.prepare('DELETE FROM menus WHERE id=? AND store_id=1').bind(id).run();if(old.image_key)await env.IMAGES.delete(old.image_key);return json({ok:true})}
async function upload(req,env){const form=await req.formData(),file=form.get('image'),types={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','image/avif':'avif'};if(!(file instanceof File)||!types[file.type])return json({error:'JPG・PNG・WebP・AVIF画像を選択してください。'},415);if(file.size>5*1024*1024)return json({error:'画像は5MB以下にしてください。'},413);const key=`menu/${new Date().toISOString().slice(0,10)}/${crypto.randomUUID()}.${types[file.type]}`;await env.IMAGES.put(key,await file.arrayBuffer(),{metadata:{contentType:file.type}});return json({key,url:`/media/${key}`},201)}
async function media(req,env,u){if(!['GET','HEAD'].includes(req.method))return new Response('Method Not Allowed',{status:405});const key=decodeURIComponent(u.pathname.slice(7));if(!key.startsWith('menu/')||key.includes('..'))return new Response('Not Found',{status:404});const {value,metadata}=await env.IMAGES.getWithMetadata(key,{type:'stream'});if(!value)return new Response('Not Found',{status:404});const h=new Headers({'content-type':metadata?.contentType||'application/octet-stream','cache-control':'public, max-age=31536000, immutable','x-content-type-options':'nosniff'});return new Response(req.method==='HEAD'?null:value,{headers:h})}
function menuError(b){if(!b.name?.trim())return'メニュー名を入力してください。';if(!Number.isInteger(Number(b.price))||Number(b.price)<0||Number(b.price)>100000)return'価格が正しくありません。';if(!['ramen','side','drink'].includes(b.category))return'カテゴリーが正しくありません。';return null}
function credentials(p){if(String(p||'').length<12)return'パスワードは12文字以上にしてください。';return null}
async function getSession(req,env){const t=cookie(req,COOKIE);if(!t)return null;return env.DB.prepare('SELECT s.user_id,u.username FROM sessions s JOIN admin_users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>CURRENT_TIMESTAMP').bind(await sha(t)).first()}
function cookie(req,n){const x=(req.headers.get('cookie')||'').split(';').map(v=>v.trim()).find(v=>v.startsWith(n+'='));return x?x.slice(n.length+1):null}
function sameOrigin(req){if(['GET','HEAD'].includes(req.method))return true;const o=req.headers.get('origin');return!!o&&o===new URL(req.url).origin}
async function body(req){if(!(req.headers.get('content-type')||'').includes('application/json'))throw Error('JSON required');return req.json()}
async function passHash(p,s,i){const k=await crypto.subtle.importKey('raw',enc.encode(p),'PBKDF2',false,['deriveBits']),bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:fromHex(s),iterations:Number(i)},k,256);return toHex(new Uint8Array(bits))}
async function sha(v){return toHex(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(v))))}function random(n){const b=new Uint8Array(n);crypto.getRandomValues(b);return toHex(b)}function toHex(b){return[...b].map(x=>x.toString(16).padStart(2,'0')).join('')}function fromHex(h){return new Uint8Array(h.match(/.{2}/g).map(x=>parseInt(x,16)))}function equal(a,b){a=String(a);b=String(b);let d=a.length^b.length;for(let i=0;i<Math.max(a.length,b.length);i++)d|=(a.charCodeAt(i)||0)^(b.charCodeAt(i)||0);return d===0}
async function fail(env,key,a){const now=Date.now(),same=a&&now-new Date(a.window_started_at).getTime()<900000,n=same?Number(a.failures)+1:1,blocked=n>=5?new Date(now+900000).toISOString():null;await env.DB.prepare('INSERT INTO login_attempts(key,failures,window_started_at,blocked_until) VALUES(?,?,?,?) ON CONFLICT(key) DO UPDATE SET failures=excluded.failures,window_started_at=excluded.window_started_at,blocked_until=excluded.blocked_until').bind(key,n,same?a.window_started_at:new Date(now).toISOString(),blocked).run()}
function json(v,s=200,x={}){return new Response(JSON.stringify(v),{status:s,headers:{...H,...x}})}
